{
 "title": "Lixee",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "lixeeserial",
    "label": "Lixee Serial Number",
    "query": {
     "query": "label_values(lixee_info, meter_serial_number)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lixee_info{meter_serial_number=\"$lixeeserial\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Tarif",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lixee_info{meter_serial_number=\"$lixeeserial\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apparent Power",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "sum by (meter_serial_number) (lixee_apparent_power {meter_serial_number=\"$lixeeserial\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lixee_rms_current_max{meter_serial_number=\"$lixeeserial\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lixee_available_power{meter_serial_number=\"$lixeeserial\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apparent Power",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "VA" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (meter_serial_number)(lixee_apparent_power{meter_serial_number=\"$lixeeserial\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (meter_serial_number)(lixee_rms_current{meter_serial_number=\"$lixeeserial\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delivered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (meter_serial_number)(lixee_current_summ_delivered{meter_serial_number=\"$lixeeserial\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}