{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.metrics.service.annotations }}
  annotations:
    {{- tpl (toYaml .Values.metrics.service.annotations) . | nindent 4 }}
  {{- end }}
  name: {{ include "exporter-lixee.fullname" . }}-metrics
  labels:
    {{- include "exporter-lixee.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: http
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "exporter-lixee.selectorLabels" . | nindent 4 }}
{{- end }}
